---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: plantuml-server
  labels:
    app.kubernetes.io/name: plantuml-server   
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: plantuml-server
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: plantuml-server
    spec:
      serviceAccountName: plantuml-server
      containers:
      - name: plantuml-server
        image: plantuml/plantuml-server:jetty-v1.2021.1
        ports:
        - name: http
          containerPort: 8080
        env:
        - name: POD_UID
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.uid
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name                                 
---
kind: Service
apiVersion: v1
metadata:
  name: plantuml
spec:
  ports:
    - name: http
      port: 8080
  selector:
    app.kubernetes.io/name: plantuml-server
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: plantuml-server